### ISSUE TITLE
Create datasets for testing

### ISSUE THREAD

**Issue by fgsch** [varnishcache-friends/libvmod-geoip2#35]
Currently we use the files from libmaxminddb.

This means that it is impossible to run `make check` from a GH created tarball (or zip) since submodules are not packaged.

One alternative is to create our own set of files that live in this repor and the tests could use.

**Comment by GeertHauwaerts** [comment]
Did you consider using adding a GitHub action to download the test files, or include script to fetch them? This is what I use in our environment (excerpt)

```
#!/bin/bash
# ...
MAXMINDTESTDB="https://github.com/maxmind/MaxMind-DB/raw/main/test-data"

MAXMINDTESTFILES=(
  'GeoIP2-City-Test'
  'GeoIP2-Connection-Type-Test'
  'GeoIP2-ISP-Test'
  'MaxMind-DB-test-decoder'
)

mkdir -p libmaxminddb/t/maxmind-db/test-data

for i in "${MAXMINDTESTFILES[@]}"; do
  wget -q -P libmaxminddb/t/maxmind-db/test-data/ "${MAXMINDTESTDB}/${i}.mmdb"
done

make check || error_exit 'Failed to make check'
# ...
```

**Comment by fgsch** [comment]
@GeertHauwaerts Nop, thanks for the suggestion. I will have a look 👍

**Comment by fgsch** [comment]
Done.
