### ISSUE TITLE
Is that possible to get as number?

### ISSUE THREAD

**Issue by iammeken** [varnishcache-friends/libvmod-geoip2#52]
Autonomous System Number
GeoLite2 ASN Database
https://dev.maxmind.com/geoip/docs/databases/asn?lang=en

It will be very helpful to block spam/scanner ASN.
Thanks!

**Comment by fgsch** [comment]
@iammeken it should be. 

Have a look at https://github.com/varnishcache-friends/libvmod-geoip2/wiki#database-details and the examples.
If the data is available in the (binary) database you should be able to query it.

**Comment by iammeken** [comment]
Thanks!  I have set it up :)

**Comment by fgsch** [comment]
Do you have a working code you can share? Might be a good idea to add it to the examples.

**Comment by iammeken** [comment]
`sub vcl_init {
new asn = geoip2.geoip2("/path/to/GeoLite2-ASN.mmdb");
}

sub vcl_recv {
set req.http.ASN = asn.lookup("autonomous_system_number", client.ip);
set req.http.ASN-ORG = asn.lookup("autonomous_system_organization", client.ip);

if (req.http.ASN-ORG ~ "(?i)XXX"){
		...
	}
}'

Do not block yourself :)
