### ISSUE TITLE
Instalation failed

### ISSUE THREAD

**Issue by teis-e** [varnishcache-friends/libvmod-geoip2#54]
![Scherm­afbeelding 2023-04-05 om 12 48 48](https://user-images.githubusercontent.com/89307927/230059280-88847a00-f3eb-4701-a8cd-28cfa7e3aa87.png)

**Comment by fgsch** [comment]
Hi. Thanks for the report. To help can you provide the following:

- Varnish version (varnishd -V output)
- libvmod-geoip2 branch
- Steps to reproduce it (optional but nice to have)

Once I have this information I'd take a look.

**Comment by teis-e** [comment]
Sure thnx!

![Scherm­afbeelding 2023-04-05 om 14 18 05](https://user-images.githubusercontent.com/89307927/230077992-87b817ee-ea4d-40b6-971d-0caeb2ce93c9.png)

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
Varnish mod directory: /usr/lib/x86_64-linux-gnu/varnish/vmods

Varnish installed from package

**Comment by fgsch** [comment]
It shouldn't fail. Can you show me the content of the test-suite.log?

**Comment by fgsch** [comment]
@teis-e  In case you missed my previous comment, it's hard to tell without more info.  
Can you provide the test-suite.log file?

**Comment by fgsch** [comment]
Timed out. Please open a new issue if you are still running into this problem.
